<a href="https://colab.research.google.com/github/tanviengineer/ai-learning-journey/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Basic array creation
# np.array() == it is a function use to create a numpy array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
list1 = [1,2,3,4,"tanvi"]
list1

[1, 2, 3, 4, 'tanvi']

In [ ]:
np.array(list1)

array(['1', '2', '3', '4', 'tanvi'], dtype='<U21')

In [ ]:
l =[[1,2,3,4],[5,6,7,8]]
l

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
np.array(l)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# AARAY GENRERATION FUNCTION
arr= np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr= np.arange(1,10,2)
arr


array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr= np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
arr= np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.linspace()

In [ ]:
# RANDOM GENRATION FUNCTION
arr= np.random.rand(10)
arr

array([0.4054205 , 0.6217119 , 0.15535038, 0.39260499, 0.2739637 ,
       0.48026722, 0.09180995, 0.34469459, 0.72861081, 0.52631137])

In [ ]:
arr =np.random.randn(10)
arr

array([ 1.42772254,  0.31767575,  0.59977455, -0.80788803,  0.26546801,
        0.49824858,  2.0358397 , -0.60033671, -0.09692506, -0.14187054])

In [ ]:
arr= np.random.randint(10)
arr

5

In [ ]:
# ARRAY ATTRIBUTES
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
# ARRAY METHOS
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.max()


np.int64(6)

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.sum()

np.int64(21)

In [ ]:
np.sum(arr,axis=0)

array([5, 7, 9])

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15])

In [ ]:
arr.mean()

np.float64(3.5)

In [ ]:
arr.std()

np.float64(1.707825127659933)

In [ ]:
# show the index number of highest value
arr.argmax()

np.int64(5)

In [ ]:
# RESHAING AND RESIZING
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [20]:
# resize: done resize when we save it in a new variable
arr= arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#  ARRAY INDEXING

In [2]:
# array indexing and slicing of veectors
import numpy as np

In [3]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

np.int64(17)

In [6]:
arr[9]

np.int64(20)

In [8]:
arr[1:7]

array([12, 13, 14, 15, 16, 17])

In [9]:
arr[1:9:2]

array([12, 14, 16, 18])

In [14]:
arr[-1:-8]

array([], dtype=int64)

In [ ]:
# array indexing and slicing of matrix

In [15]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr[0]

array([1, 2, 3, 4, 5])

In [23]:
# first word is row and second is colume
arr[0,1]

np.int64(2)

In [24]:
arr[0,3]

np.int64(4)

In [27]:
# first row starting to ending, then second colume starting to ending

arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [28]:
arr[3:6,2:4]

array([[18, 19],
       [23, 24],
       [28, 29]])

In [31]:
sliceing = arr[3:6,3:5]
sliceing

array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
arr[0:6,2]

array([ 3,  8, 13, 18, 23, 28])

In [35]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
# boolean indexing

In [53]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
bool_index= arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [60]:
arr = np.arange(11,21)
bool_index = arr%2==0
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [ ]:
# --------ARRAY OPERATIONS-------

In [ ]:
# Airthmetic operations

In [62]:
a1 = np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [65]:
arr=a1+a2
arr

array([ 7,  9, 11, 13, 15])

In [64]:
a1-a2

array([-5, -5, -5, -5, -5])

In [66]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [67]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [68]:
a1//a2

array([0, 0, 0, 0, 0])

In [69]:
a1%a2

array([1, 2, 3, 4, 5])

In [70]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
# Broadcasting
# used to add value in all the numbers present in the list

In [76]:
l=[1,2,3,4,5,6]
arr =np.array(l)

In [77]:
arr+10

array([11, 12, 13, 14, 15, 16])

In [82]:
arr2= np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
arr2 +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
# Deep And Shallow copy

In [85]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [87]:
# shallow copy
slice =a[:5]
slice= slice*10
slice

array([10, 20, 30, 40, 50])

In [88]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:

a[:4]*10


array([10, 20, 30, 40])

In [91]:
a
b=a

In [92]:
b[0]=99

In [93]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# deep copy

In [ ]:
# MAtrix operations

In [97]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [104]:
a

array([[1, 2],
       [3, 4]])

In [99]:
b

array([[5, 6],
       [7, 8]])

In [100]:
a*b
# it give us a wrong ans

array([[ 5, 12],
       [21, 32]])

In [101]:
a @ b
# this is the right way to multiply matrix

array([[19, 22],
       [43, 50]])

In [102]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [106]:
# transpose
# moving the full box
# row became a colume and colume became row
a.T

array([[1, 3],
       [2, 4]])

In [ ]:
# ---Advance array manipulation---

In [ ]:
# Stacking array
# in which we only vectore array and cannot use horizontal array

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [110]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [111]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [113]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# Spitting Array

In [114]:
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [115]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [116]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]