In [ ]:
import numpy as np

In [ ]:
# Basic array creation
# np.array() == it is a function use to create a numpy array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
list1 = [1,2,3,4,"tanvi"]
list1

[1, 2, 3, 4, 'tanvi']

In [ ]:
np.array(list1)

array(['1', '2', '3', '4', 'tanvi'], dtype='<U21')

In [ ]:
l =[[1,2,3,4],[5,6,7,8]]
l

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
np.array(l)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# AARAY GENRERATION FUNCTION
arr= np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr= np.arange(1,10,2)
arr


array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr= np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
arr= np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.linspace()

In [ ]:
# RANDOM GENRATION FUNCTION
arr= np.random.rand(10)
arr

array([0.4054205 , 0.6217119 , 0.15535038, 0.39260499, 0.2739637 ,
       0.48026722, 0.09180995, 0.34469459, 0.72861081, 0.52631137])

In [ ]:
arr =np.random.randn(10)
arr

array([ 1.42772254,  0.31767575,  0.59977455, -0.80788803,  0.26546801,
        0.49824858,  2.0358397 , -0.60033671, -0.09692506, -0.14187054])

In [ ]:
arr= np.random.randint(10)
arr

5

In [39]:
# ARRAY ATTRIBUTES
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr.shape

(2, 3)

In [41]:
arr.size

6

In [42]:
arr.dtype

dtype('int64')

In [43]:
# ARRAY METHOS
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr.max()


np.int64(6)

In [46]:
arr.min()

np.int64(1)

In [47]:
arr.sum()

np.int64(21)

In [48]:
np.sum(arr,axis=0)

array([5, 7, 9])

In [49]:
np.sum(arr,axis=1)

array([ 6, 15])

In [50]:
arr.mean()

np.float64(3.5)

In [51]:
arr.std()

np.float64(1.707825127659933)

In [53]:
# show the index number of highest value
arr.argmax()

np.int64(5)

In [54]:
# RESHAING AND RESIZING
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [58]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# resize: done resize when we save it in a new variable
arr= arr.reshape(6,5)

In [ ]:
#